// This file is generated by 'plone-compile-resources'

module.exports = function(grunt) {
  'use strict';
  var lessPaths = [
    './src/redturtle/patterns/slider/browser/static/pattern.less',
  ];
  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    requirejs: {
      'tiles-management-bundle': {
        options: {
          baseUrl: '/',
          generateSourceMaps: true,
          preserveLicenseComments: false,
          paths: {
            jquery: 'empty:',
            'pat-base': 'empty:',
            'slick.min': '/Users/cekk/progetti/spazzatura/redturtle.patterns.slider/src/redturtle/patterns/libraries/slick/slick.min',
            'redturtle-patterns-slider-bundle': '/src/redturtle/patterns/slider/static/',
            // 'redturtle-patterns-slider': '/src/redturtle/patterns/slider/static/pattern',
            'redturtle-patterns-slider': '/Users/cekk/progetti/spazzatura/redturtle.patterns.slider/src/redturtle/patterns/static/pattern'
          },
          // shim: {'less': {}, 'text': {}, },
          wrapShim: true,
          name: '/Users/cekk/progetti/spazzatura/redturtle.patterns.slider/src/redturtle/patterns/static/bundle.js',
          exclude: ['jquery'],
          out: '/Users/cekk/progetti/spazzatura/redturtle.patterns.slider/src/redturtle/patterns/slider/static/redturtle-patterns-slider-bundle-compiled.js',
          optimize: 'none',
        },
      },
    },
    uglify: {
      'redturtle-pat': {
        options: {
          sourceMap: true,
          sourceMapName: './src/redturtle/patterns/slider/browser/static/redturtle-patterns-slider-compiled.js.map',
          sourceMapIncludeSources: false,
        },
        files: {
          './src/redturtle/patterns/slider/static/redturtle-patterns-slider-compiled.js': ['./src/redturtle/patterns/slider/static/redturtle-patterns-slider-bundle-compiled.js'],
        },
      },
    },
  });

  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-requirejs');
  grunt.loadNpmTasks('grunt-contrib-less');
  grunt.loadNpmTasks('grunt-contrib-uglify');

  // grunt.loadNpmTasks('grunt-sed');

  grunt.registerTask('default', ['watch']);
  grunt.registerTask('compile', ['requirejs', 'uglify']);

  grunt.registerTask('compile-redturtle-tiles-management', [
    'requirejs:tiles-management-bundle',
    'less:redturtle-tiles-management',
    'uglify:redturtle-tiles-management',
  ]);
};
